### ISSUE TITLE
Security: Inloggen met Google auth

### ISSUE THREAD

**Issue by Laoujin** [be-pongit/confac-front#2]
Implementeer eerst het inloggen in de frontend;
Het effectief blokkeren van de site zal helemaal op het einde gebeuren zodat de site bruikbaar blijft terwijl security half geïmplementeerd is

* [x] Inloggen via Google met @itenium.be emails: Gebruik een package 😃

Van Google krijg je dan typisch een "secret", dat stuur je naar de backend 
* [x] een nieuwe controller /user/login: die genereert een JWT met ons eigen secret (ons secret zit in configuratie!) 
--> of check eens wat internet voorstelt als best practice...

* [x] het token is tot 23:59:59 van de huidige dag geldig. 
* [x] Deze JWT wordt naar de frontend gegeven en moet dan op elke request naar de backend gestuurd worden.
- * [x] sla het JWT op in sessionStorage aan de frontend
- * [x] api requests: zorg dat je een soort van injector of interceptor hebt (of een helper functie) zodat alle frontend calls nu met JWT zijn: Authorization header = "Bearer base64encodedJWT"
- * [x] attachment requests: ook downloads van attachments moet rechten afgecheckt worden!
- * [x] bij checken JWT aan de backend: zorg ervoor dat je het token ook valideert!

Content JWT:
- userId
- roles: string[]

* [x] Collection Users
- _id
- name
- email
- roles: string[]
- language: 'nl' (aangezien we momenteel enkel nl hebben)
- active

* [x] Collection Roles
- _id
- name
- desc
- claims: string[]
- active

Bij opstart backend:
* [x] if (UsersCollection is empty): seed with default users: jij en ik
* [x] if (roles is empty): seed with default roles

```
{name: 'consultant', claims: []}

{name: 'user', claims: ['view-clients', 'view-projects', 'view-config', 'edit-quotations']}

{name: 'resource-manager', claims: ['manage-clients', 'manage-projects, 'manage-quotations']} (+ user)

{name: 'monthly-invoicing', claims: ['edit-projectMonth']} (+ user + resource-manager)

{name: 'bookkeeper', claims: [ 'view-invoices', 'edit-invoice', 'delete-invoice', 'validate-invoice', 'email-invoice', 'create-projectsMonth', 'manage-projectsMonth'] (+ user + resource-manager + monthly-invoicing)

{name: 'admin', claims: ['manage-users', 'manage-roles', 'manage-config']}
```

With permissions:
* view-config: view Config, Users, Roles
* edit-quotations: create & edit (your) quotations
* edit-projectMonth: can edit existing projectMonth but not validate timesheet, validate inbound invoice (creating the invoice is create-invoice)

Bij opstarten frontend: 
* [x] ophalen van de Users (enkel _id, name en email ophalen) -> stop dit in de redux store
* [x] Ophalen van de Roles -> stop dit in de redux store EN stop het ook in localStorage. Als het in de localStorage zit, gebruik dat dan als default value voor de reducer

* [x] Een nieuwe pagina aan de frontend /profile: toon icon in de header die naar deze pagina leidt (toon nu gewoon de content van de JWT op die pagina)

* [x] /config krijgt een aantal knoppen voor componenten;
- * [x] UsersList & EditUserModal (/config/users)
- * [x] RolesList & EditRoleModal (/config/roles)
--> Modals: er hoeven geen aparte edit pagina's voor te zijn.

* [x] Het id van de huidige gebruiker opslaan als "createdBy" voor invoices, offertes, projecten, consultants en klanten (maak een IAudit { string createdBy; string createdOn, string lastModifiedBy, lastModifiedOn } --> Door de interface zal de code om deze velden te zetten slechts 1x geïmplementeerd worden!!
* [x] Visualiseer dit aan de frontend (zoals op de EditInvoice pagina)

And finally:
- [x] geen ingelogd user -> redirect naar login pagina

**Comment by Laoujin** [comment]
Mocht hier aan begonnen worden: Er is al een PR in front/backend waar een deel geïmplementeerd is door Kevin.

**Comment by Laoujin** [comment]
Also solves:
https://github.com/be-pongit/confac-front/issues/32
