### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by Laoujin** [be-pongit/confac-front#37]
**ProjectsMonth Listing**

Het is 1 grote editeerbare tabel.

Als je vastzit (vb: wachtend op functionele feedback), check dan voor andere bugs/changes op: https://github.com/be-pongit/confac-front/issues/66

**De wireframes:**

[confac-projectsMonth-2.pdf](https://github.com/be-pongit/confac-front/files/4037991/confac-projectsMonth-2.pdf)
[confac-projectsMonth-1.pdf](https://github.com/be-pongit/confac-front/files/4037992/confac-projectsMonth-1.pdf)
[confac-projectsMonth-3.pdf](https://github.com/be-pongit/confac-front/files/4037993/confac-projectsMonth-3.pdf)

**De technische analyse**

Maak een tekening van hoe je de componenten structuur zou doen voor de ProjectsMonthTable van scherm 4 van de eerste wireframes
--> We zullen je "technische analyse"  zodra je ze hebt dan op de standup bespreken
--> Die analyse is "weggooi": je hoeft er dus niet teveel tijd aan te spenderen - is de bedoeling om te gebruiken als communicatie over hoe je het zou aanpakken

Geen backend, enkel frontend: Backend gaan we pas doen nadat de backed geupgrade is.

**PR 1: Het skelet**

Maak een skelet zodat je bijvoorbeeld aan de Timesheet kolommen en aan de inbound invoice kolommen tegelijkertijd kan werken.

**Volgende PRs?**

Misschien 1 PR voor Timesheet en 1 voor Inbound en outbound?

**Comment by Laoujin** [comment]
Work with a "Send Pay Month"?

**Comment by Laoujin** [comment]
Original drawings :)

![confac-projects-3](https://user-images.githubusercontent.com/2582910/72027394-24ed7a80-327f-11ea-8dd1-c4fd886046e3.png)
![confac-projects-4](https://user-images.githubusercontent.com/2582910/72027395-24ed7a80-327f-11ea-8a69-4cab934a51e1.png)

**Comment by Laoujin** [comment]
**LEGACY ANALYSES**

**Projects**:  

- [x] New main category "Project" (hide offertes behind invoices?)
- [x] Types: freelancer, consultant, external consultant
- [x] Common Fields: Name, Company
- [ ] Consultants: == See intake doc
- [ ] Freelancers: == Freelancer company
- [ ] Check CRM for fields Placement there
- [x] Creating a new consultant results in "tasks"
- [x] Create monthly tasks button
	- Per freelancer / consultant
	- General stuff
- [x] Config Facturenlijst "Consultant"


**Tasks**:  
- [ ] MinDate, MaxDate
- [ ] Attachments
- [ ] Mail notifications
- [ ] Assigned to

Example:
- Mail that it's time to order the car
- ...
